Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Copyright (c) 2013 by Krzemin.
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
  approot: "http://typeinf.herokuapp.com"
  analytics: UA-41507531-1
  